// Tüm arayüz metinleri. Sadece Türkçe, i18n altyapısı yok (PROMPT "Kapsam dışı").
// Paylaşılan dosya: frontend ve backend anahtar ekler → Read → Edit, çakışmada yeniden oku (max 3).
// Her task kendi bölümünü ekler; mevcut anahtarları yeniden adlandırma.

export const tr = {
  app: {
    name: "Lead Radar",
    tagline: "Web sitesi olmayan işletmeleri bulun",
  },
  nav: {
    dashboard: "Dashboard",
    businesses: "İşletmeler",
    searches: "Aramalar",
    settings: "Ayarlar",
    logout: "Çıkış",
  },
  common: {
    save: "Kaydet",
    cancel: "Vazgeç",
    delete: "Sil",
    loading: "Yükleniyor…",
    error: "Bir hata oluştu",
    copySuccess: "Panoya kopyalandı",
    copyError: "Kopyalanamadı",
  },
  errors: {
    unauthorized: "Oturum gerekli",
    validation: "Geçersiz istek",
    notFound: "Kayıt bulunamadı",
    internal: "Sunucu hatası",
    invalidPassword: "Şifre hatalı",
    missingEnv: "Zorunlu ortam değişkeni eksik veya geçersiz",
    settingNotFound: "Bilinmeyen ayar anahtarı",
    templateNotFound: "Şablon bulunamadı",
    emptyUpdate: "Güncellenecek en az bir alan gönderin",
    businessNotFound: "İşletme bulunamadı",
    invalidTransition: "Bu durum geçişine izin verilmiyor",
    confirmationRequired: "Bu geçiş onay gerektiriyor",
    nothingToUndo: "Geri alınacak durum değişikliği yok",
    undoWithOtherFields: "Geri alma başka alanlarla birlikte gönderilemez",
    placesNotConfigured:
      "Google Places API anahtarı tanımlı değil (GOOGLE_PLACES_API_KEY) — .env'ye ekleyin veya PLACES_MOCK=1 kullanın",
    placesUnavailable: "Google Places'a ulaşılamadı, daha sonra tekrar deneyin",
    placesRateLimited: "Google Places istek sınırı aşıldı (429), birkaç dakika sonra tekrar deneyin",
    placesInvalidResponse: "Google Places beklenmeyen bir yanıt döndü",
    placesRequestFailed: (status: number) => `Google Places isteği başarısız oldu (HTTP ${status})`,
    unknownCity: "Şehir ayarlardaki listede yok",
    unknownDistrict: "İlçe seçilen ile ait değil",
    searchJobNotFound: "Arama işi bulunamadı",
    searchFailed: "Arama işi başarısız oldu",
    searchInterrupted: "Sunucu yeniden başladığı için arama işi yarıda kaldı",
    invalidPhotoName: "Geçersiz fotoğraf adı",
    photoUnavailable: "Fotoğraf alınamadı",
  },
  export: {
    sheetName: "İşletmeler",
    columns: {
      name: "İşletme",
      category: "Kategori",
      city: "Şehir",
      district: "İlçe",
      address: "Adres",
      phone: "Telefon",
      email: "E-posta",
      websiteUri: "Mevcut link",
      websiteKind: "Link türü",
      rating: "Puan",
      userRatingCount: "Yorum Sayısı",
      score: "Lead Skoru",
      status: "Durum",
      lastContactedAt: "Son Temas",
      googleMapsUri: "Google Maps URL",
      photoUrl: "Fotoğraf 1 URL",
      notes: "Notlar",
    },
    /** "Link türü" sütunu; marka varsa "Sosyal medya (Instagram)" */
    websiteKind: {
      NONE: "Yok",
      SOCIAL: "Sosyal medya",
      PLATFORM: "Platform",
      WEBSITE: "Web sitesi",
    },
  },
  status: {
    NEW: "Yeni",
    QUALIFIED: "Nitelikli",
    CONTACTED: "Temas edildi",
    REPLIED: "Cevap verdi",
    MEETING: "Görüşme",
    WON: "Kazanıldı",
    LOST: "Kaybedildi",
    SKIPPED: "Atlandı",
  },
  statusConfirm: {
    recontact: "Bu işletme daha önce reddetti / atlandı. Yine de temas mı?",
  },
  scoreBands: {
    HOT: "Sıcak",
    WARM: "Ilık",
    COLD: "Soğuk",
  },
  scoreSignals: {
    reviewCount: "Yorum sayısı",
    rating: "Puan",
    photos: "Fotoğraf",
    phone: "Telefon",
    recency: "Son yorum",
    category: "Kategori bonusu",
  },
  auth: {
    subtitle: "Devam etmek için şifreyi girin",
    passwordLabel: "Şifre",
    passwordPlaceholder: "Şifrenizi girin",
    submit: "Giriş yap",
    submitting: "Giriş yapılıyor…",
    genericError: "Giriş yapılamadı, tekrar deneyin",
  },
  panel: {
    dashboard: {
      title: "Dashboard",
      placeholder: "Dashboard kartları ve grafik özetleri TASK-109'da eklenecek.",
    },
    businesses: {
      title: "İşletmeler",
      placeholder: "İşletme tablosu TASK-106'da eklenecek.",
    },
    searches: {
      title: "Aramalar",
      placeholder: "Arama geçmişi ve ilerleme takibi TASK-105'te eklenecek.",
    },
    menuOpen: "Menüyü aç",
    menuClose: "Menüyü kapat",
    logoutError: "Çıkış yapılamadı, tekrar deneyin",
  },
  settings: {
    title: "Ayarlar",
    description: "Şehirler, bonus kategoriler ve mesaj şablonlarını buradan yönetin.",
    loadError: "Ayarlar yüklenemedi",
    requestError: "İstek başarısız oldu",
    places: {
      title: "Places API durumu",
      description: "API anahtarı sunucu ortam değişkenlerinden okunur.",
      configured: "Anahtar tanımlı ✓",
      notConfigured: "Anahtar tanımlı değil ✗",
      mockMode: "Mock mod aktif",
      note: "Places API anahtarı burada gösterilmez veya girilmez; yalnızca .env dosyasından okunur.",
    },
    cities: {
      title: "Şehirler",
      description: "Arama formunda görünecek şehir listesi.",
      inputPlaceholder: "Yeni şehir adı",
      add: "Ekle",
      empty: "Henüz şehir eklenmedi.",
      updateError: "Şehir listesi güncellenemedi",
      addError: "Şehir eklenemedi, aynı isim zaten olabilir",
      duplicate: "Bu şehir zaten listede",
    },
    bonusCategories: {
      title: "Bonus kategoriler",
      description: "Bu kategorilerdeki işletmeler Lead Skoru'na +10 puan alır.",
      inputPlaceholder: "Places kategori değeri (örn. restaurant)",
      add: "Ekle",
      empty: "Henüz kategori eklenmedi.",
      updateError: "Kategori listesi güncellenemedi",
      addError: "Kategori eklenemedi, aynı değer zaten olabilir",
      duplicate: "Bu kategori zaten listede",
      rescoreButton: "Skorları yeniden hesapla",
      rescoreSuccess: (updated: number) => `${updated} işletme güncellendi`,
      rescoreError: "Skorlar yeniden hesaplanamadı",
    },
    templates: {
      title: "Mesaj şablonları",
      description: "İlk temas mesajlarınız için hazır şablonlar.",
      newButton: "Yeni şablon",
      editButton: "Düzenle",
      deleteButton: "Sil",
      empty: "Henüz şablon eklenmedi.",
      loadError: "Şablonlar yüklenemedi",
      optOutMissingBadge: "Opt-out cümlesi eksik",
      channelWhatsapp: "WhatsApp",
      channelEmail: "E-posta",
      deleteConfirmTitle: "Şablonu sil",
      deleteConfirmDescription: "Bu şablon kalıcı olarak silinecek. Bu işlem geri alınamaz.",
      formTitleNew: "Yeni şablon",
      formTitleEdit: "Şablonu düzenle",
      formNameLabel: "Ad",
      formNamePlaceholder: "Örn. İlk temas — WhatsApp",
      formChannelLabel: "Kanal",
      formBodyLabel: "Mesaj metni",
      formBodyPlaceholder: "Mesaj metnini yazın…",
      placeholdersLabel: "Yer tutucular (tıklayınca imlece eklenir)",
      placeholderPlatformHint: "Instagram, Booking.com vb.; link yoksa \"sosyal medya\"",
      optOutWarning:
        "Bu şablonda opt-out cümlesi görünmüyor (örn. \"istemiyorsanız bildirin\"). Yine de kaydedebilirsiniz.",
      createSuccess: "Şablon oluşturuldu",
      updateSuccess: "Şablon güncellendi",
      deleteSuccess: "Şablon silindi",
      saveError: "Şablon kaydedilemedi",
      deleteError: "Şablon silinemedi",
    },
  },
  searches: {
    title: "Aramalar",
    description: "Google Haritalar'da web sitesi olmayan işletmeleri tarayın.",
    form: {
      categoryLabel: "Kategori",
      categoryPlaceholder: "Örn. berber, restoran, diş kliniği",
      pickFromList: "Listeden seç",
      categorySearch: "Kategori ara…",
      categoryEmpty: "Listede yok — kutuya serbestçe yazabilirsiniz",
      categoryGroups: {
        lodging: "Konaklama",
        food: "Yeme-içme",
        beauty: "Güzellik ve bakım",
        health: "Sağlık",
        professional: "Profesyonel hizmetler",
        auto: "Otomotiv",
        home: "Ev ve yapı hizmetleri",
        retail: "Perakende",
        education: "Eğitim ve spor",
        events: "Etkinlik ve düğün",
      },
      cityLabel: "Şehir",
      cityPlaceholder: "Şehir seçin",
      districtLabel: "İlçe (opsiyonel)",
      categoryHint:
        "Büyük şehirlerde ilçe seçin — Google her sorguda en fazla 60 sonuç verir.",
      mapToggleLabel: "Haritadan alan seç",
      mapHint:
        "Haritaya tıklayarak arama merkezini belirleyin, işaretçiyi sürükleyerek taşıyabilirsiniz. Bu modda Google sorgusuna şehir/ilçe eklenmez, yalnızca çizdiğiniz alan taranır.",
      radiusLabel: "Yarıçap",
      areaNotSelected: "Haritadan bir merkez seçin",
      submit: "Tara",
      submitting: "Taranıyor…",
      validationError: "Kategori ve şehir zorunlu",
      categoryRequired: "Kategori yazın veya listeden seçin",
      cityRequired: "Şehir seçin",
      areaCityAuto: (city: string) => `Kayıt şehri: ${city} (haritadan belirlendi)`,
      placesWarning:
        "Places API anahtarı tanımlı değil — .env'e GOOGLE_PLACES_API_KEY ekleyin veya PLACES_MOCK=1 ile çalıştırın.",
      settingsLink: "Ayarlar'a git",
    },
    progress: {
      runningTitle: "Arama sürüyor",
      doneTitle: "Arama tamamlandı",
      failedTitle: "Arama başarısız",
      scanned: "tarandı",
      withoutWebsite: "sitesiz",
      saved: "kaydedildi",
      estimatedCost: "Tahmini maliyet",
      viewResults: "Sonuçları gör",
      linkOnlySuffix: (linkOnly: number) => `(${linkOnly}'i yalnız sosyal medya / platform)`,
      summary: (scanned: number, withoutWebsite: number) =>
        `${scanned} tarandı, ${withoutWebsite} sitesiz`,
      areaBadge: "Harita alanı",
    },
    history: {
      title: "Geçmiş aramalar",
      empty: "Henüz arama yapılmadı.",
      loadError: "Arama geçmişi yüklenemedi",
    },
    table: {
      query: "Sorgu",
      city: "Şehir",
      status: "Durum",
      scanned: "Tarandı",
      withoutWebsite: "Sitesiz",
      saved: "Kaydedildi",
      cost: "Maliyet",
      startedAt: "Başlangıç",
      duration: "Süre",
      statusRunning: "Sürüyor",
      statusDone: "Tamamlandı",
      statusFailed: "Başarısız",
      linkOnlySuffix: (linkOnly: number) => `(${linkOnly} sosyal)`,
      areaSuffix: (radius: string) => `Harita alanı · ${radius}`,
    },
  },
  dashboard: {
    title: "Dashboard",
    description: "İşletme portföyünüzün ve satış sürecinizin özeti.",
    loadError: "Dashboard verisi yüklenemedi",
    cards: {
      businesses: "Toplam işletme",
      hot: "Sıcak lead",
      contactedThisWeek: "Bu hafta temas",
      replyRate: "Cevap oranı",
      won: "Kazanılan",
      totalCost: "Toplam API maliyeti",
    },
    funnel: {
      title: "Satış hunisi",
    },
    recentSearches: {
      title: "Son aramalar",
    },
    empty: {
      title: "Henüz veri yok",
      description: "İlk taramayı başlatarak websitesiz işletmeleri bulmaya başlayın.",
      cta: "İlk taramayı başlat",
    },
  },
  businesses: {
    filters: {
      cityLabel: "Şehir",
      cityAll: "Tüm şehirler",
      districtLabel: "İlçe",
      categoryLabel: "Kategori",
      categoryPlaceholder: "Kategori ara (örn. restoran)",
      statusLabel: "Durum",
      statusAll: "Tüm durumlar",
      bandLabel: "Skor bandı",
      bandAll: "Tüm bantlar",
      webLabel: "Site durumu",
      webAll: "Tümü",
      webNone: "Link yok",
      webSocial: "Sadece sosyal medya",
      webPlatform: "Platform profili",
      webWebsite: "Web sitesi var",
      searchPlaceholder: "İsim veya telefon ara…",
      sortLabel: "Sırala",
      sortScore: "Skora göre",
      sortReviews: "Yorum sayısına göre",
      sortRecent: "Eklenme tarihine göre",
    },
    columns: {
      photo: "Fotoğraf",
      name: "İşletme",
      category: "Kategori",
      city: "Şehir",
      phone: "Telefon",
      email: "E-posta",
      rating: "Puan / Yorum",
      score: "Lead Skoru",
      status: "Durum",
      lastContact: "Son temas",
      actions: "İşlemler",
    },
    empty: {
      title: "Henüz işletme yok",
      description: "Aramalar'dan tarama başlatın.",
      action: "Aramalar'a git",
    },
    loadError: "İşletmeler yüklenemedi",
    stale: "Veri eski",
    staleTooltip: "Google verisi 30 günden eski, detaydan yenileyin.",
    noPhone: "—",
    whatsappAria: "WhatsApp'ta aç",
    noEmail: "E-posta ekle",
    emailInvalid: "Geçersiz e-posta adresi",
    emailUpdateError: "E-posta güncellenemedi",
    statusUpdateError: "Durum güncellenemedi",
    statusConfirmTitle: "Onay gerekiyor",
    statusConfirmAction: "Yine de devam et",
    pagination: {
      range: (from: number, to: number, total: number) => `${from}–${to} / ${total}`,
      prev: "Önceki",
      next: "Sonraki",
    },
    selection: {
      count: (n: number) => `${n} seçildi`,
      exportSelected: "Excel'e aktar",
      exportFiltered: "Filtreli listeyi Excel'e aktar",
      changeStatus: "Durumu değiştir",
      statusPlaceholder: "Durum seçin",
      apply: "Uygula",
      bulkResult: (updated: number, skipped: number) => `${updated} güncellendi, ${skipped} atlandı`,
      bulkError: "Toplu işlem başarısız",
      bulkDelete: "Seçilenleri sil",
      bulkDeleteTitle: (n: number) => `${n} işletme silinecek`,
      bulkDeleteDescription:
        "Notlar ve durum geçmişi de silinir; işletmeler sonraki aramalarda yeniden bulunabilir.",
      bulkDeleteSuccess: (n: number) => `${n} işletme silindi`,
      bulkDeleteError: "Toplu silme başarısız",
    },
    delete: {
      menuLabel: "Sil",
      title: "İşletmeyi sil",
      description: (name: string) =>
        `"${name}" silinecek. Notlar ve durum geçmişi de silinir; işletme sonraki aramalarda yeniden bulunabilir.`,
      cancel: "Vazgeç",
      confirm: "Sil",
      success: (name: string) => `"${name}" silindi`,
      error: "İşletme silinemedi",
    },
  },
  detail: {
    loadError: "İşletme yüklenemedi",
    gallery: {
      empty: "Fotoğraf yok",
    },
    refresh: {
      button: "Yenile",
      loading: "Yenileniyor…",
      success: "Veri güncellendi",
      unavailable: "Places API yapılandırılmamış",
      error: "Yenilenemedi",
    },
    contact: {
      title: "İletişim",
      addressEmpty: "Adres bilgisi yok",
      call: "Ara",
      copy: "Kopyala",
      whatsapp: "WhatsApp",
      maps: "Haritada aç",
      emailPlaceholder: "E-posta ekleyin",
    },
    overview: {
      title: "Puan ve saatler",
      hoursEmpty: "Çalışma saatleri paylaşılmamış",
      ratingEmpty: "Henüz puan yok",
    },
    reviews: {
      title: "Yorumlar",
      empty: "Henüz yorum yok",
      more: "Devamını oku",
      less: "Daralt",
    },
    score: {
      title: "Skor kırılımı",
      total: "Toplam",
    },
    template: {
      title: "Mesaj şablonu",
      selectPlaceholder: "Şablon seçin",
      loadError: "Şablonlar yüklenemedi",
      copy: "Kopyala",
      copyWhatsapp: "Kopyala + WhatsApp'ı aç",
      copyEmail: "Kopyala + E-postayı aç",
      statusUpdated: "Durum: İletişime geçildi",
      undo: "Geri al",
      undoSuccess: "Geri alındı",
      undoError: "Geri alınamadı",
    },
    history: {
      title: "Durum geçmişi",
      empty: "Henüz durum değişikliği yok",
      arrow: "→",
    },
    notes: {
      title: "Notlar",
      placeholder: "Not ekle… (Ctrl/Cmd+Enter ile kaydet)",
      add: "Not ekle",
      empty: "Henüz not yok",
      addError: "Not eklenemedi",
    },
    delete: {
      button: "İşletmeyi sil",
    },
  },
  website: {
    kinds: {
      NONE: "Link yok",
      SOCIAL: "Sosyal medya",
      PLATFORM: "Platform profili",
      WEBSITE: "Web sitesi var",
    },
  },
  cityPicker: {
    placeholder: "Şehir seçin",
    search: "Şehir ara…",
    empty: "Şehir bulunamadı",
    groupKktc: "KKTC",
    groupTurkey: "Türkiye",
    groupOther: "Diğer",
    districtAll: "Tüm ilçeler",
    districtPlaceholder: "İlçe seçin",
    districtSearch: "İlçe ara…",
    districtEmpty: "İlçe bulunamadı",
  },
} as const;
