// Tüm arayüz metinleri. Sadece Türkçe, i18n altyapısı yok (PROMPT "Kapsam dışı").
// Paylaşılan dosya: frontend ve backend anahtar ekler → Read → Edit, çakışmada yeniden oku (max 3).
// Her task kendi bölümünü ekler; mevcut anahtarları yeniden adlandırma.

export const tr = {
  app: {
    name: "Lead Radar",
    tagline: "Web sitesi olmayan işletmeleri bulun",
  },
  nav: {
    dashboard: "Dashboard",
    businesses: "İşletmeler",
    searches: "Aramalar",
    settings: "Ayarlar",
    logout: "Çıkış",
  },
  common: {
    save: "Kaydet",
    cancel: "Vazgeç",
    delete: "Sil",
    loading: "Yükleniyor…",
    error: "Bir hata oluştu",
  },
  errors: {
    unauthorized: "Oturum gerekli",
    validation: "Geçersiz istek",
    notFound: "Kayıt bulunamadı",
    internal: "Sunucu hatası",
    invalidPassword: "Şifre hatalı",
    missingEnv: "Zorunlu ortam değişkeni eksik veya geçersiz",
    settingNotFound: "Bilinmeyen ayar anahtarı",
    templateNotFound: "Şablon bulunamadı",
    emptyUpdate: "Güncellenecek en az bir alan gönderin",
  },
  status: {
    NEW: "Yeni",
    QUALIFIED: "Nitelikli",
    CONTACTED: "Temas edildi",
    REPLIED: "Cevap verdi",
    MEETING: "Görüşme",
    WON: "Kazanıldı",
    LOST: "Kaybedildi",
    SKIPPED: "Atlandı",
  },
  statusConfirm: {
    recontact: "Bu işletme daha önce reddetti / atlandı. Yine de temas mı?",
  },
  scoreBands: {
    HOT: "Sıcak",
    WARM: "Ilık",
    COLD: "Soğuk",
  },
  scoreSignals: {
    reviewCount: "Yorum sayısı",
    rating: "Puan",
    photos: "Fotoğraf",
    phone: "Telefon",
    recency: "Son yorum",
    category: "Kategori bonusu",
  },
  auth: {
    subtitle: "Devam etmek için şifreyi girin",
    passwordLabel: "Şifre",
    passwordPlaceholder: "Şifrenizi girin",
    submit: "Giriş yap",
    submitting: "Giriş yapılıyor…",
    genericError: "Giriş yapılamadı, tekrar deneyin",
  },
  panel: {
    dashboard: {
      title: "Dashboard",
      placeholder: "Dashboard kartları ve grafik özetleri TASK-109'da eklenecek.",
    },
    businesses: {
      title: "İşletmeler",
      placeholder: "İşletme tablosu TASK-106'da eklenecek.",
    },
    searches: {
      title: "Aramalar",
      placeholder: "Arama geçmişi ve ilerleme takibi TASK-105'te eklenecek.",
    },
    menuOpen: "Menüyü aç",
    menuClose: "Menüyü kapat",
    logoutError: "Çıkış yapılamadı, tekrar deneyin",
  },
  settings: {
    title: "Ayarlar",
    description: "Şehirler, bonus kategoriler ve mesaj şablonlarını buradan yönetin.",
    loadError: "Ayarlar yüklenemedi",
    requestError: "İstek başarısız oldu",
    places: {
      title: "Places API durumu",
      description: "API anahtarı sunucu ortam değişkenlerinden okunur.",
      configured: "Anahtar tanımlı ✓",
      notConfigured: "Anahtar tanımlı değil ✗",
      mockMode: "Mock mod aktif",
      note: "Places API anahtarı burada gösterilmez veya girilmez; yalnızca .env dosyasından okunur.",
    },
    cities: {
      title: "Şehirler",
      description: "Arama formunda görünecek şehir listesi.",
      inputPlaceholder: "Yeni şehir adı",
      add: "Ekle",
      empty: "Henüz şehir eklenmedi.",
      updateError: "Şehir listesi güncellenemedi",
      addError: "Şehir eklenemedi, aynı isim zaten olabilir",
      duplicate: "Bu şehir zaten listede",
    },
    bonusCategories: {
      title: "Bonus kategoriler",
      description: "Bu kategorilerdeki işletmeler Lead Skoru'na +10 puan alır.",
      inputPlaceholder: "Places kategori değeri (örn. restaurant)",
      add: "Ekle",
      empty: "Henüz kategori eklenmedi.",
      updateError: "Kategori listesi güncellenemedi",
      addError: "Kategori eklenemedi, aynı değer zaten olabilir",
      duplicate: "Bu kategori zaten listede",
      rescoreButton: "Skorları yeniden hesapla",
      rescoreSuccess: (updated: number) => `${updated} işletme güncellendi`,
      rescoreError: "Skorlar yeniden hesaplanamadı",
    },
    templates: {
      title: "Mesaj şablonları",
      description: "İlk temas mesajlarınız için hazır şablonlar.",
      newButton: "Yeni şablon",
      editButton: "Düzenle",
      deleteButton: "Sil",
      empty: "Henüz şablon eklenmedi.",
      loadError: "Şablonlar yüklenemedi",
      optOutMissingBadge: "Opt-out cümlesi eksik",
      channelWhatsapp: "WhatsApp",
      channelEmail: "E-posta",
      deleteConfirmTitle: "Şablonu sil",
      deleteConfirmDescription: "Bu şablon kalıcı olarak silinecek. Bu işlem geri alınamaz.",
      formTitleNew: "Yeni şablon",
      formTitleEdit: "Şablonu düzenle",
      formNameLabel: "Ad",
      formNamePlaceholder: "Örn. İlk temas — WhatsApp",
      formChannelLabel: "Kanal",
      formBodyLabel: "Mesaj metni",
      formBodyPlaceholder: "Mesaj metnini yazın…",
      placeholdersLabel: "Yer tutucular (tıklayınca imlece eklenir)",
      optOutWarning:
        "Bu şablonda opt-out cümlesi görünmüyor (örn. \"istemiyorsanız bildirin\"). Yine de kaydedebilirsiniz.",
      createSuccess: "Şablon oluşturuldu",
      updateSuccess: "Şablon güncellendi",
      deleteSuccess: "Şablon silindi",
      saveError: "Şablon kaydedilemedi",
      deleteError: "Şablon silinemedi",
    },
  },
} as const;
